// ═══════════════════════════════════════════════════
//  SOBRALBUS — BANCO DE DADOS DOS VEÍCULOS
//  Edite este arquivo para adicionar/remover veículos
//  Execute: node gerar-paginas.js após cada alteração
// ═══════════════════════════════════════════════════

const catalogo = [
  {
    slug:       "comil-invictus-dd-mb-o500-rsd",
    titulo:     "Comil Invictus DD — MB O500 RSDD",
    marca:      "Comil",
    chassi:     "Mercedes-Benz O500 RSDD",
    ano:        2019,
    km:         "1.000.000",
    lugares:    43,
    preco:      "R$ 1.150.000",
    precoNum:   1150000,
    categoria:  "rodoviario",
    destaque:   true,
    ativo:      true,
    imagem:     "../assets/rodoviario/acz/A.png",
    ogImagem:   "https://sobralbus.com.br/assets/rodoviario/acz/A.png",
    andares:    "2 (Duplo DD)",
    descricao:  "Um dos ônibus mais robustos do catálogo. O chassi Mercedes-Benz O500 RSDD combinado com a carroceria Comil Invictus configuração Double Deck entrega alto padrão de conforto. Ideal para linhas interestaduais de longa distância.",
    specs: [
      { key: "Carroceria",       val: "Comil Invictus DD" },
      { key: "Chassi",           val: "Mercedes-Benz O500 RSDD" },
      { key: "Ano",              val: "2019" },
      { key: "Quilometragem",    val: "1.000.000 km" },
      { key: "Andares",          val: "2 (Duplo DD)" },
      { key: "Lugares",          val: "43" },
      { key: "Ar-condicionado",  val: "Duplo" },
      { key: "Combustível",      val: "Diesel" },
      { key: "Câmbio",           val: "Automático" },
      { key: "Tipo",             val: "Rodoviário" },
      { key: "Estado",           val: "Sobral — CE" },
      { key: "Documentação",     val: "Em dia" },
    ],
    badges:     ["Destaque", "Rodoviário"],
    imagens:    [
      "../assets/rodoviario/acz/A.png",
      "../assets/rodoviario/acz/B.png",
      "../assets/rodoviario/acz/C.png",
    ],
    whatsapp:   "Olá,%20tenho%20interesse%20no%20Comil%20Invictus%20DD%20MB%20O500%20RSDD",
  },
  {
    slug:       "marcopolo-g7-1050",
    titulo:     "Marcopolo G7 1050 — MB O500 RS",
    marca:      "Marcopolo",
    chassi:     "Mercedes-Benz O500 RS 360 CV",
    ano:        2019,
    km:         "1.000.000",
    lugares:    44,
    preco:      "R$ 420.000",
    precoNum:   420000,
    categoria:  "rodoviario",
    destaque:   false,
    ativo:      true,
    imagem:     "../assets/rodoviario/g7-1050/B.png",
    ogImagem:   "https://sobralbus.com.br/assets/rodoviario/g7-1050/B.png",
    andares:    "1",
    descricao:  "Ônibus rodoviário Marcopolo G7 1050 sobre chassi Mercedes-Benz O500 RS 360 CV. Ideal para linhas interestaduais e fretamento executivo.",
    specs: [
      { key: "Carroceria",       val: "Marcopolo G7 1050" },
      { key: "Chassi",           val: "Mercedes-Benz O500 RS 360 CV" },
      { key: "Ano",              val: "2019" },
      { key: "Quilometragem",    val: "1.000.000 km" },
      { key: "Lugares",          val: "44" },
      { key: "Combustível",      val: "Diesel" },
      { key: "Câmbio",           val: "Mecânico" },
      { key: "Tipo",             val: "Rodoviário" },
      { key: "Estado",           val: "Sobral — CE" },
      { key: "Documentação",     val: "Em dia" },
    ],
    badges:     ["Rodoviário"],
    imagens:    [
      "../assets/rodoviario/g7-1050/B.png",
      "../assets/rodoviario/g7-1050/C.png",
    ],
    whatsapp:   "Olá,%20tenho%20interesse%20no%20Marcopolo%20G7%201050",
  },
     {
    slug:       "comil-pia-micro",
    titulo:     "Comil Piá - MB - LO 916",
    marca:      "Comil",
    chassi:     "Mercedes-Benz LO 916",
    ano:        2016,
    km:         "394.590",
    lugares:    31,
    preco:      "R$ 320.000",
    precoNum:   320000,
    categoria:  "micro",
    destaque:   false,
    ativo:      true,
    imagem:     "../assets/micro-onibus/comil-pia/A.png",
    ogImagem:   "https://sobralbus.com.br/assets/micro-onibus/comil-pia/A.png",
    descricao:  "Comil Piá 2016 – Mercedes-Benz LO 916 Ideal para fretamento, transporte escolar, turismo e transporte corporativo. Capacidade para 31 passageiros + motorista, oferecendo conforto e praticidade. Equipado com ar-condicionado Spheros, porta-pacotes interno e cabine cabinada. Conta com carregadores USB em todas as poltronas e vidros móveis. Possui câmbio mecânico de 5 marchas + ré, garantindo economia e confiabilidade operacional.",
    specs: [
      { key: "Carroceria", val: "Comil" },
      { key: "Chassi", val: "Mercedes-Benz 916" },
      { key: "Ano", val: "2016" },
      { key: "Quilometragem", val: "394.590" },
      { key: "Lugares", val: "31" },
      { key: "Combustível", val: "Diesel" },
      { key: "Câmbio", val: "Mecânico" },
      { key: "Tipo", val: "Micro" },
      { key: "Estado", val: "Sobral — CE" },
      { key: "Documentação", val: "Em dia" },
      { key: "Banheiro", val: "Não" },
      { key: "Carregador USB", val: "Sim" },
      { key: "Ar-Condicionado", val: "Sim (Spheros)" },
    ],
    badges:     ["Micro"],
    imagens:    [
    "../assets/micro-onibus/comil-pia/A.png",
    "../assets/micro-onibus/comil-pia/B.png",
    "../assets/micro-onibus/comil-pia/C.png",
    "../assets/micro-onibus/comil-pia/D.png",
    "../assets/micro-onibus/comil-pia/E.png",
    "../assets/micro-onibus/comil-pia/F.png",
    "../assets/micro-onibus/comil-pia/G.png",
    "../assets/micro-onibus/comil-pia/H.png",
    "../assets/micro-onibus/comil-pia/I.png",
    "../assets/micro-onibus/comil-pia/J.png",
    "../assets/micro-onibus/comil-pia/K.png",
    "../assets/micro-onibus/comil-pia/L.png",
    "../assets/micro-onibus/comil-pia/M.png",
    "../assets/micro-onibus/comil-pia/N.png",
    "../assets/micro-onibus/comil-pia/O.png",
    "../assets/micro-onibus/comil-pia/P.png",
    "../assets/micro-onibus/comil-pia/Q.png",
    "../assets/micro-onibus/comil-pia/R.png"
    ],
    whatsapp:   "Olá,%20tenho%20interesse%20no%20micro%20Comil%20Piá%202016%20no%20valor%20de%20R$320.000,00.%20Gostaria%20de%20mais%20informações.",
  },
];

module.exports = { catalogo };
